repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: scripts/run-tool mypy src tests
        language: script
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: scripts/run-tool pytest
        language: script
        pass_filenames: false
        stages: [pre-push]
