"""Shared fixtures for the auto_border_pano test suite."""

from PIL import Image


def synthetic_panorama(width: int = 3000, height: int = 800) -> Image.Image:
    """Build a deterministic gradient panorama for tests.

    Deterministic so that failures are reproducible and so that reference
    outputs can be regenerated byte-for-byte.
    """
    img = Image.new("RGB", (width, height))
    pixels = img.load()
    assert pixels is not None
    for x in range(width):
        for y in range(height):
            pixels[x, y] = (x % 256, y % 256, (x + y) % 256)
    return img
