"""Shared fixtures for the auto_border_pano test suite.

The GUI stubs that used to live here went with the tkinter build. Qt tests
use `pytest-qt`'s `qtbot`, which supplies a session `QApplication` and real
widgets, so nothing has to be faked.
"""

import os

from PIL import Image

# Set before any test module imports Qt. The GUI tests build real widgets,
# and without this they open windows on the desktop of whoever is running
# the suite -- and fail outright anywhere without a display.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")


def synthetic_panorama(width: int = 3000, height: int = 800) -> Image.Image:
    """Build a deterministic gradient panorama for tests.

    Deterministic so that failures are reproducible and so that reference
    outputs can be regenerated byte-for-byte.
    """
    img = Image.new("RGB", (width, height))
    pixels = img.load()
    assert pixels is not None
    for x in range(width):
        for y in range(height):
            pixels[x, y] = (x % 256, y % 256, (x + y) % 256)
    return img
